BugTracker/Models/BugViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using WebMatrix.WebData;
using BugTracker.DAL;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace BugTracker.Models
{
    public class BugViewModel
    {
        public int BugId { get; set; }
        public int TesterId { get; set; }
        public int ProjectId { get; set; }
        public int StatusId { get; set; }
        public int PriorityId { get; set; }

        [Display(Name="Tester")]
        public string TesterName { get; set; }

        [Display(Name="Project")]
        public string ProjectName { get; set; }

        [Required]
        [Display(Name="Priority")]
        public string Priority { get; set; }

        [Required]
        [Display(Name="Status")]
        public string Status { get; set; }

        [Display(Name="Date Of Discovery")]
        [DataType(DataType.DateTime)]
        public DateTime DiscoverDate { get; set; }

        [Required]
        [Display(Name="Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public BugViewModel()
        {
        }

        public BugViewModel(Bug bug)
        {
            this.BugId = bug.BugId;
            this.TesterId = ((bug.UserId == null) ? (0) : ((int) bug.UserId) );
            this.TesterName = ((bug.UserId == null) ? ("No Author") : (bug.UserProfile.UserName));
            this.ProjectId = bug.ProjectId;
            this.ProjectName = bug.Project.ProjectName;
            this.Priority = bug.Priority;
            this.PriorityId = GetPriorityId(this.Priority);
            this.Status = bug.Status;
            this.StatusId = GetStatusId(this.Status);
            this.DiscoverDate = bug.DiscoverDate;
            this.Description = bug.Description;
        }

        //I know this isn't the best way, but I'm out of time
        //I think it would be better to implement the states and priorities in the DataBase
        private int GetStatusId(string str)
        {
            switch (str)
            {
                case "New": return 1;
                case "In Progress": return 2;
                case "Fixed": return 3;
                case "Closed": return 4;
                default: return 0;
            }
        }

        private int GetPriorityId(string str)
        {
            switch (str)
            {
                case "Critical": return 1;
                case "High": return 2;
                case "Normal": return 3;
                case "Low": return 4;
                default: return 0;
            }
        }
    }

    public class CreateBugViewModel
    {
        [Required]
        public int ProjectId { get; set; }

        [Display(Name="Project")]
        public string ProjectName { get; set; }

        public int TesterId { get; set; }
        
        [Display(Name="Tester")]
        public string TesterName { get; set; }

        [Required]
        [Display(Name="Priority")]
        public string Priority { get; set; }

        [Required]
        [Display(Name="Status")]
        public string Status { get; set; }

        [Display(Name="Date Of Discovery")]
        public DateTime DiscoverDate { get; set; }

        [Required]
        [Display(Name="Description")]
        public string Description { get; set; }

        public CreateBugViewModel()
        {
            this.TesterId = WebSecurity.CurrentUserId;
            this.TesterName = WebSecurity.CurrentUserName;
            this.Priority = "Normal";
            this.Status = "New";
            this.DiscoverDate = DateTime.Now;
        }
    }
}

BugTracker/Controllers/BugController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BugTracker.DAL;
using BugTracker.Models;
using WebMatrix.WebData;
using PagedList;

namespace BugTracker.Controllers
{
    [Authorize]
    public class BugController : Controller
    {
        //
        // GET: /Bug/

        public ActionResult Index()
        {   
            return View();
        }

        public ActionResult SelectProject(int projectId = 0)
        {
            ViewBag.ProjectsList = new SelectList(CreateListOfProjects(), "ProjectId", "ProjectName", projectId);
            return View();
        }

        public ActionResult ListBugsByProject(int projectId = 0, string sortOrder = "Date", int page = 1)
        {
            ViewBag.ProjectsList = new SelectList(CreateListOfProjects(), "ProjectId", "ProjectName", projectId);

            List<BugViewModel> bugs = new List<BugViewModel>();

            if (projectId == 0)
            {
                bugs = CreateListOfBugs(BugDAL.ListAllBugs());
            }
            else
            {
                bugs = CreateListOfBugs(BugDAL.ListBugsByProjectId(projectId));
            }

            bugs = SortBugs(bugs, sortOrder);

            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.TesterSortParm = sortOrder == "Tester" ? "Tester desc" : "Tester";
            ViewBag.ProjectSortParm = sortOrder == "Project" ? "Project desc" : "Project";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date desc" : "Date";
            ViewBag.PrioritySortParm = sortOrder == "Priority" ? "Priority desc" : "Priority";
            ViewBag.StatusSortParm = sortOrder == "Status" ? "Status desc" : "Status";

            int pageSize = 15;

            return View(bugs.ToPagedList<BugViewModel>(page, pageSize));
        }

        //
        // GET: /Bug/Details/5

        public ActionResult Details(int id = 0)
        {
            Bug bugDB = BugDAL.GetBugById(id);
            if (bugDB == null)
            {
                return RedirectToAction("DeletedBug");
            }

            BugViewModel bug = new BugViewModel(bugDB);
            return View(bug);
        }

        //
        // GET: /Bug/Create

        public ActionResult Create(string returnAction)
        {
            ViewBag.ReturnAction = returnAction;

            List<ProjectViewModel> projects = new List<ProjectViewModel>();
            foreach (var item in ProjectDAL.ListAllProjects())
            {
                projects.Add(new ProjectViewModel(item));
            }
            ViewBag.ProjectId = new SelectList(projects, "ProjectId", "ProjectName");

            ViewBag.PriorityList = new SelectList(PriorityList);
            //List<UserProfileViewModel> testers = new List<UserProfileViewModel>();
            //foreach (var item in UserProfileDAL.ListAllUserProfiles())
            //{
            //    testers.Add(new UserProfileViewModel(item));
            //}
            //ViewBag.UserId = new SelectList(testers, "UserId", "UserName");

            CreateBugViewModel bug = new CreateBugViewModel();
            return View(bug);
        }

        //
        // POST: /Bug/Create

        [HttpPost]
        public ActionResult Create(CreateBugViewModel bug, string returnAction)
        {
            if (ModelState.IsValid)
            {
                BugDAL.AddBug(
                    bug.TesterId,
                    bug.ProjectId,
                    bug.Priority,
                    bug.Status,
                    bug.DiscoverDate,
                    bug.Description);

                InfoCardDAL.AddBugToInfoCard(bug.TesterId, bug.ProjectId);

                return RedirectToAction( returnAction);
            }

            List<ProjectViewModel> projects = new List<ProjectViewModel>();
            foreach (var item in ProjectDAL.ListAllProjects())
            {
                projects.Add(new ProjectViewModel(item));
            }
            ViewBag.ProjectId = new SelectList(projects, "ProjectId", "ProjectName", bug.ProjectId);

            ViewBag.PriorityList = new SelectList(PriorityList);
            //ViewBag.UserId = new SelectList(UserProfileDAL.ListAllUserProfiles(), "UserId", "UserName", bug.TesterId);
            return View(bug);
        }

        //
        // GET: /Bug/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Bug bugDB = BugDAL.GetBugById(id);
            if (bugDB == null)
            {
                return RedirectToAction("DeletedBug");
            }

            BugViewModel bug = new BugViewModel(bugDB);

            ViewBag.StatusList = new SelectList(StatusList, bug.Status);
            ViewBag.PriorityList = new SelectList(PriorityList, bug.Priority);
            
            return View(bug);
        }

        //
        // POST: /Bug/Edit/5

        [HttpPost]
        public ActionResult Edit(BugViewModel bug)
        {
            if (ModelState.IsValid)
            {
                BugDAL.UpdateBug(
                    bug.BugId,
                    bug.Priority,
                    bug.Status,
                    bug.Description
                    );

                InfoCardDAL.UpdateBugInfoCard(WebSecurity.CurrentUserId, bug.BugId, "Edited");

                return RedirectToAction("Index");
            }

            ViewBag.StatusList = new SelectList(StatusList, bug.Status);
            ViewBag.PriorityList = new SelectList(PriorityList, bug.Priority);

            return View(bug);
        }

        //
        // GET: /Bug/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Bug bugDB = BugDAL.GetBugById(id);
            if (bugDB == null)
            {
                return RedirectToAction("DeletedBug");
            }

            BugViewModel bug = new BugViewModel(bugDB);

            return View(bug);
        }

        //
        // POST: /Bug/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BugDAL.RemoveBug(id);

            InfoCardDAL.UpdateBugInfoCard(WebSecurity.CurrentUserId, id, "Deleted");

            return RedirectToAction("Index");
        }

        public ActionResult DeletedBug()
        {
            return View();
        }


        #region Helpers

        private List<BugViewModel> SortBugs(List<BugViewModel> bugs , string sortOrder)
        {
            if (sortOrder == "")
            {
                sortOrder = "Date";
            }
            switch (sortOrder)
            {
                case "Date":
                    bugs = bugs.OrderBy(x => x.DiscoverDate).ToList();
                    break;
                case "Date desc":
                    bugs = bugs.OrderByDescending(x => x.DiscoverDate).ToList();
                    break;
                case "Tester":
                    bugs = bugs.OrderBy(x => x.TesterName).ToList();
                    break;
                case "Tester desc":
                    bugs = bugs.OrderByDescending(x => x.TesterName).ToList();
                    break;
                case "Project":
                    bugs = bugs.OrderBy(x => x.ProjectName).ToList();
                    break;
                case "Project desc":
                    bugs = bugs.OrderByDescending(x => x.ProjectName).ToList();
                    break;
                case "Priority":
                    bugs = bugs.OrderBy(x => x.PriorityId).ToList();
                    break;
                case "Priority desc":
                    bugs = bugs.OrderByDescending(x => x.PriorityId).ToList();
                    break;
                case "Status":
                    bugs = bugs.OrderBy(x => x.StatusId).ToList();
                    break;
                case "Status desc":
                    bugs = bugs.OrderByDescending(x => x.StatusId).ToList();
                    break;
                default:
                    bugs = bugs.OrderBy(x => x.DiscoverDate).ToList();
                    break;
            }
            return bugs;
        }

        private List<ProjectViewModel> CreateListOfProjects()
        {
            List<ProjectViewModel> projects = new List<ProjectViewModel>();
            foreach (var item in ProjectDAL.ListAllProjects())
            {
                projects.Add(new ProjectViewModel(item));
            }
            projects = projects.OrderBy(x => x.ProjectName).ToList();

            //Insert a project indicating all projects
            projects.Insert(0, new ProjectViewModel(0, "All projects", "List all projects"));

            return projects;
        }

        private List<BugViewModel> CreateListOfBugs(List<Bug> bugsDB)
        {
            List<BugViewModel> bugs = new List<BugViewModel>();
            foreach (var bug in bugsDB)
            {
                bugs.Add(new BugViewModel(bug));
            }

            return bugs;
        }

        public List<string> StatusList = new List<string> 
        {
            "New",
            "In Progress",
            "Fixed",
            "Closed"
        };

        public List<string> PriorityList = new List<string>
        {
            "Critical",
            "High",
            "Normal",
            "Low"
        };
        #endregion
    }
}

BugTracker/Views/Bug/Create.cshtml
@model BugTracker.Models.CreateBugViewModel

@{
    ViewBag.Title = "Create";
    SelectList projects = ViewBag.ProjectId;
    SelectList statusList = ViewBag.StatusList;
    SelectList priorityList = ViewBag.PriorityList;
}

<h2>Create</h2>

@using (Html.BeginForm(new { returnAction = ViewBag.ReturnAction }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bug</legend>

        <div class="display-label">
            @Html.LabelFor(model => model.DiscoverDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.DiscoverDate)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.TesterName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TesterName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectId, "Project")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProjectId", projects)
            @Html.ValidationMessageFor(model => model.ProjectId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Priority)
        </div>
        <div class="editor-field">
            @Html.DropDownList("Priority", priorityList)
            @Html.ValidationMessageFor(model => model.Priority)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="textarea-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Add Bug" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Cancel", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BugTracker/Views/Bug/Delete.cshtml
@model BugTracker.Models.BugViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Bug</legend>

    <div class="display-label">
         @Html.LabelFor(model => model.TesterName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TesterName)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.ProjectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectName)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.DiscoverDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DiscoverDate)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.Priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Priority)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

BugTracker/Views/Bug/DeletedBug.cshtml
@{
    ViewBag.Title = "DeletedBug";
}

<h2 class="error">Error</h2>

<br />
<div class="error">
    This bug doesn't exist or was deleted!
</div>

<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BugTracker/Views/Bug/Details.cshtml
@model BugTracker.Models.BugViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details for bug @Html.DisplayFor(model => model.BugId)</h2>

<fieldset>
    <legend>Bug</legend>

    <div class="display-label">
         @Html.LabelFor(model => model.DiscoverDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DiscoverDate)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.TesterName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TesterName)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.ProjectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectName)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.Priority)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Priority)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>
    <br />

    <div class="display-label">
         @Html.LabelFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.BugId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BugTracker/Views/Bug/Edit.cshtml
@model BugTracker.Models.BugViewModel

@{
    ViewBag.Title = "Edit";
    SelectList statusList = ViewBag.StatusList;
    SelectList priorityList = ViewBag.PriorityList;
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bug</legend>

        @Html.HiddenFor(model => model.BugId)

        <div class="display-label">
            @Html.LabelFor(model => model.DiscoverDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.DiscoverDate)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.TesterName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TesterName)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.ProjectName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.ProjectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.DropDownList("Status", statusList)
            @Html.ValidationMessageFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Priority)
        </div>
        <div class="editor-field">
            @Html.DropDownList("Priority", priorityList)
            @Html.ValidationMessageFor(model => model.Priority)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BugTracker/Views/Bug/Index.cshtml
@model List<BugTracker.Models.BugViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add New Bug", "Create", new { returnAction = "Index" })
</p>

<p>
    @Html.ActionLink("List Bugs", "SelectProject")
</p>

BugTracker/Views/Bug/ListBugsByProject.cshtml
@model PagedList.IPagedList<BugTracker.Models.BugViewModel>
@{
    ViewBag.Title = "ListBugsByProject";
    SelectList projects = ViewBag.ProjectsList;
}

<h2>List Bugs By Project</h2>

@using (Html.BeginForm("ListBugsByProject", "Bug", new { projectId = projects.SelectedValue, sortOrder = ViewBag.CurrentSortOrder, page = 1 }))
{
    <fieldset>
        <legend class="editor-label">
            @Html.Label("Select Project")
        </legend>
        <div class="editor-field">
            Select Project: @Html.DropDownList("ProjectId", projects)
            <input type="submit" value="List" />
        </div>

    </fieldset>
}
<p>
    @Html.ActionLink("Add New Bug", "Create", new { returnAction = "ListBugsByProject" })
</p>
<table>
    <tr>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().TesterName).ToString(), "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.TesterSortParm, page = Model.PageNumber })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().ProjectName).ToString(), "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.ProjectSortParm, page = Model.PageNumber })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().DiscoverDate).ToString(), "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.DateSortParm, page = Model.PageNumber })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().Priority).ToString(), "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.PrioritySortParm, page = Model.PageNumber })
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().Status).ToString(), "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.StatusSortParm, page = Model.PageNumber })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TesterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscoverDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayTextFor(modelItem => item.Description).ToString().Substring(0, (item.Description.Length < 50) ? item.Description.Length : 50)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BugId }) |
            @Html.ActionLink("Details", "Details", new { id = item.BugId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.BugId })
            </td>
        </tr>
    }

</table>

<br />

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount

    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.CurrentSortOrder, page = 1 })
        @Html.Raw(" ");
        @Html.ActionLink("< Prev", "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.CurrentSortOrder, page = Model.PageNumber - 1 })
    }
    else
    {
        @:<<
        @Html.Raw(" ");
        @:< Prev
    }

    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.CurrentSortOrder, page = Model.PageNumber + 1 })
        @Html.Raw(" ");
        @Html.ActionLink(">>", "ListBugsByProject", new { projectId = projects.SelectedValue, sortOrder = ViewBag.CurrentSortOrder, page = Model.PageCount })
    }
    else
    {
        @:Next >
        @Html.Raw(" ")
        @:>>
    }
</div>

BugTracker/Views/Bug/SelectProject.cshtml
@{
    ViewBag.Title = "SelectProject";
    SelectList projects = ViewBag.ProjectsList;
}

<h2>SelectProject</h2>

@using (Html.BeginForm("ListBugsByProject", "Bug", new { projectId = projects.SelectedValue }))
{
    <fieldset>
        <legend class="editor-label">
            @Html.Label("Select Project")
        </legend>
        <div class="editor-field">
            Select Project: @Html.DropDownList("ProjectId", projects)
            <input type="submit" value="List" />
        </div>

    </fieldset>
}